### ISSUE TITLE
RapidAPI source code

### ISSUE THREAD

**Issue by 89z** [awesome-yasin/Media-Downloader#1]
Do you have the source code for this server?

https://github.com/awesome-yasin/Media-Downloader/blob/02df4382c1ef02de6a76f35a5a7a81e153e7a69b/Instagram%20Downloader%20V2/src/components/Post.jsx#L35-L45

**Comment by nitinkumar30** [comment]
You just have to paste your API key in `your-key` field. Find the screenshot below from the link [here].(https://rapidapi.com/studio/api_a9626adb-c6c5-43d9-88ad-01231a2cdba8/publish/gateway)

![image](https://user-images.githubusercontent.com/40369168/191902407-ec39e3ed-276c-4e02-8122-ed70226bddd0.png)
